name: Stuff and things

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image:  cirrusci/flutter:stable

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt-get -y update
          apt-get -y install make

      - name: stuff
        run: make format

      - name: Print Dart SDK version
        run: dart --version

      - name: format
        run: make format

      - name: analyze
        run: make analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run tests
        run: dart test
