name: Stuff and things

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  cirrusci/flutter:stable
    steps:
      - uses: actions/checkout@v2
      - name: Print Dart SDK version
        run: dart --version
      - name: format
        run: make format
      - name: analyze
        run: make analyze
